/*
 * SPI_Config.c
 *
 * Created: 3/4/2023 2:16:24 PM
 *  Author: Lord
 */ 

#include "SPI_Config.h"




void SPI_Vconfig()
{
	#if (DATA_ORDER_CONFIG == DATA_FROM_LSB_FIRST)
		SET_BIT(SPCR,DORD_BIT);
	#elif (DATA_ORDER_CONFIG == DATA_FROM_MSB_FIRST)
		CLEAR_BIT(SPCR,DORD_BIT);
	#endif
	
	
	#if (CURRENT_CONFIG_M_OR_S == MASTER_MODE)
		SET_BIT(SPCR,MSTR_BIT);	
		#if (CURRENT_CLK_RATE == CLK_RATE_OVER_4)
			CLEAR_BIT(SPCR,SPR_0_BIT);
			CLEAR_BIT(SPCR,SPR_1_BIT);
			CLEAR_BIT(SPCR,SPI2X_BIT);
		#elif (CURRENT_CLK_RATE == CLK_RATE_OVER_16)
			SET_BIT(SPCR,SPR_0_BIT);
			CLEAR_BIT(SPCR,SPR_1_BIT);
			CLEAR_BIT(SPCR,SPI2X_BIT);
		#elif (CURRENT_CLK_RATE == CLK_RATE_OVER_64)
			CLEAR_BIT(SPCR,SPR_0_BIT);
			SET_BIT(SPCR,SPR_1_BIT);
			CLEAR_BIT(SPCR,SPI2X_BIT);
		#elif (CURRENT_CLK_RATE == CLK_RATE_OVER_128)
			SET_BIT(SPCR,SPR_0_BIT);
			SET_BIT(SPCR,SPR_1_BIT);
			CLEAR_BIT(SPCR,SPI2X_BIT);
		#elif (CURRENT_CLK_RATE == CLK_RATE_OVER_2)
			CLEAR_BIT(SPCR,SPR_0_BIT);
			CLEAR_BIT(SPCR,SPR_1_BIT);
			SET_BIT(SPCR,SPI2X_BIT);
		#elif (CURRENT_CLK_RATE == CLK_RATE_OVER_8)
			SET_BIT(SPCR,SPR_0_BIT);
			CLEAR_BIT(SPCR,SPR_1_BIT);
			SET_BIT(SPCR,SPI2X_BIT);
		#elif (CURRENT_CLK_RATE == CLK_RATE_OVER_32_2)
			CLEAR_BIT(SPCR,SPR_0_BIT);
			SET_BIT(SPCR,SPR_1_BIT);
			SET_BIT(SPCR,SPI2X_BIT);
		#elif (CURRENT_CLK_RATE == CLK_RATE_OVER_64_2)
			SET_BIT(SPCR,SPR_0_BIT);
			SET_BIT(SPCR,SPR_1_BIT);
			SET_BIT(SPCR,SPI2X_BIT);
		#endif	
	#elif (CURRENT_CONFIG_M_OR_S == SLAVE_MODE)
		CLEAR_BIT(SPCR,MSTR_BIT);
	#endif
	
	
	
	#if (CURRENT_CLK_POLARITY ==CLK_POLARITY_RISING )
		CLEAR_BIT(SPCR,CPOL_BIT);
	#elif (CURRENT_CLK_POLARITY ==CLK_POLARITY_FALLING )
		SET_BIT(SPCR,CPOL_BIT);
	#endif
	
	
	#if (CURRENT_CLK_PHASE == CLK_POLARITY_PHASE_SAMPLE_LEAD)
		CLEAR_BIT(SPCR,CPHA_BIT);
	#elif (CURRENT_CLK_PHASE == CLK_POLARITY_PHASE_SETUP_LEAD)
		SET_BIT(SPCR,CPHA_BIT);
	#endif
	
	
}