/*
 * adc_config.c
 *
 * Created: 2/25/2023 11:36:23 AM
 *  Author: Lord
 */ 

#include "adc_config.h"

void adc_vconfig ()
{
	
	//Voltage Reference Configuration
	#if (VOLTAGE_REFERENCE_CFG == AREF)
		CLEAR_BIT(ADMUX,REFS0_BIT);
		CLEAR_BIT(ADMUX,REFS1_BIT);
	#elif (VOLTAGE_REFERENCE_CFG == AVCC)
		SET_BIT(ADMUX,REFS0_BIT);
		CLEAR_BIT(ADMUX,REFS1_BIT);
	#elif (VOLTAGE_REFERENCE_CFG == INTERNAL)
		SET_BIT(ADMUX,REFS0_BIT);
		SET_BIT(ADMUX,REFS1_BIT);
	#endif
	
	// Right or Left Adjustment
	#if (ADJUSTMENT_CFG == LEFT_ADJUSTMENT)
		SET_BIT(ADMUX,ADLAR_BIT);
	#elif (ADJUSTMENT_CFG == RIGHT_ADJUSTMENT)
		CLEAR_BIT(ADMUX,ADLAR_BIT);
	#endif
	
	//Choose Analog Input Channel
	
	
	#if (ADC_ANALOG_INPUT_CHANNEL_CFG == DIO_U8_PIN_0)
		CLEAR_BIT(ADMUX,MUX0_BIT);
		CLEAR_BIT(ADMUX,MUX1_BIT);
		CLEAR_BIT(ADMUX,MUX2_BIT);
		CLEAR_BIT(ADMUX,MUX3_BIT);
		CLEAR_BIT(ADMUX,MUX4_BIT);
		dio_vidConfigChannel(DIO_PORTA,DIO_PIN0,INPUT);
	#elif (ADC_ANALOG_INPUT_CHANNEL_CFG == DIO_U8_PIN_1)
		SET_BIT(ADMUX,MUX0_BIT);
		CLEAR_BIT(ADMUX,MUX1_BIT);
		CLEAR_BIT(ADMUX,MUX2_BIT);
		CLEAR_BIT(ADMUX,MUX3_BIT);
		CLEAR_BIT(ADMUX,MUX4_BIT);
		dio_vidConfigChannel(DIO_PORTA,DIO_PIN1,INPUT);
	#elif (ADC_ANALOG_INPUT_CHANNEL_CFG == DIO_U8_PIN_2)
		CLEAR_BIT(ADMUX,MUX0_BIT);
		SET_BIT(ADMUX,MUX1_BIT);
		CLEAR_BIT(ADMUX,MUX2_BIT);
		CLEAR_BIT(ADMUX,MUX3_BIT);
		CLEAR_BIT(ADMUX,MUX4_BIT);
		dio_vidConfigChannel(DIO_PORTA,DIO_PIN2,INPUT);
	#elif (ADC_ANALOG_INPUT_CHANNEL_CFG == DIO_U8_PIN_3)
		SET_BIT(ADMUX,MUX0_BIT);
		SET_BIT(ADMUX,MUX1_BIT);
		CLEAR_BIT(ADMUX,MUX2_BIT);
		CLEAR_BIT(ADMUX,MUX3_BIT);
		CLEAR_BIT(ADMUX,MUX4_BIT);
		dio_vidConfigChannel(DIO_PORTA,DIO_PIN3,INPUT);
	#elif (ADC_ANALOG_INPUT_CHANNEL_CFG == DIO_U8_PIN_4)
		CLEAR_BIT(ADMUX,MUX0_BIT);
		CLEAR_BIT(ADMUX,MUX1_BIT);
		SET_BIT(ADMUX,MUX2_BIT);
		CLEAR_BIT(ADMUX,MUX3_BIT);
		CLEAR_BIT(ADMUX,MUX4_BIT);
		dio_vidConfigChannel(DIO_PORTA,DIO_PIN4,INPUT);
	#elif (ADC_ANALOG_INPUT_CHANNEL_CFG == DIO_U8_PIN_5)
		SET_BIT(ADMUX,MUX0_BIT);
		CLEAR_BIT(ADMUX,MUX1_BIT);
		SET_BIT(ADMUX,MUX2_BIT);
		CLEAR_BIT(ADMUX,MUX3_BIT);
		CLEAR_BIT(ADMUX,MUX4_BIT);
		dio_vidConfigChannel(DIO_PORTA,DIO_PIN5,INPUT);
	#elif (ADC_ANALOG_INPUT_CHANNEL_CFG == DIO_U8_PIN_6)
		CLEAR_BIT(ADMUX,MUX0_BIT);
		SET_BIT(ADMUX,MUX1_BIT);
		SET_BIT(ADMUX,MUX2_BIT);
		CLEAR_BIT(ADMUX,MUX3_BIT);
		CLEAR_BIT(ADMUX,MUX4_BIT);
		dio_vidConfigChannel(DIO_PORTA,DIO_PIN6,INPUT);
	#elif (ADC_ANALOG_INPUT_CHANNEL_CFG == DIO_U8_PIN_7)
		SET_BIT(ADMUX,MUX0_BIT);
		SET_BIT(ADMUX,MUX1_BIT);
		SET_BIT(ADMUX,MUX2_BIT);
		CLEAR_BIT(ADMUX,MUX3_BIT);
		CLEAR_BIT(ADMUX,MUX4_BIT);
		dio_vidConfigChannel(DIO_PORTA,DIO_PIN7,INPUT);
	#endif
	
	
	
	/*  ( if / else if ) condition for Macros */
	#if RUNNING_MODE_CFG == FREE_RUNNING_MODE
		CLEAR_BIT( SFIOR , ADTS0_BIT );
		CLEAR_BIT( SFIOR , ADTS1_BIT );
		CLEAR_BIT( SFIOR , ADTS2_BIT );
	
	#elif RUNNING_MODE_CFG == ANALOG_COMPARATOR_MODE
		SET_BIT( SFIOR , ADTS0_BIT );
		CLEAR_BIT( SFIOR , ADTS1_BIT );
		CLEAR_BIT( SFIOR , ADTS2_BIT );
	
	#elif RUNNING_MODE_CFG == EXTERNAL_INTERRUPT_REQUEST_0_MODE
		CLEAR_BIT( SFIOR , ADTS0_BIT );
		SET_BIT( SFIOR , ADTS1_BIT );
		CLEAR_BIT( SFIOR , ADTS2_BIT );
	
	
	#elif RUNNING_MODE_CFG == TMR0_CTR0_COMPARE_MODE
		SET_BIT( SFIOR , ADTS0_BIT );
		SET_BIT( SFIOR , ADTS1_BIT );
		CLEAR_BIT( SFIOR , ADTS2_BIT );

	#elif RUNNING_MODE_CFG == TMR0_CTR0_OVERFLOW_MODE
		CLEAR_BIT( SFIOR , ADTS0_BIT );
		CLEAR_BIT( SFIOR , ADTS1_BIT );
		SET_BIT( SFIOR , ADTS2_BIT );
	
	#elif RUNNING_MODE_CFG == TMR1_CTR1_COMPARE_MATCH_B_MODE
		SET_BIT( SFIOR , ADTS0_BIT );
		CLEAR_BIT( SFIOR , ADTS1_BIT );
		SET_BIT( SFIOR , ADTS2_BIT );

	#elif RUNNING_MODE_CFG == TMR1_CTR1_OVERFLOW_MODE
		CLEAR_BIT( SFIOR , ADTS0_BIT );
		SET_BIT( SFIOR , ADTS1_BIT );
		SET_BIT( SFIOR , ADTS2_BIT );

	#elif RUNNING_MODE_CFG == TMR1_CTR1_CAPTURE_EVENT_MODE
		SET_BIT( SFIOR , ADTS0_BIT );
		SET_BIT( SFIOR , ADTS1_BIT );
		SET_BIT( SFIOR , ADTS2_BIT );
	
	#endif
	/* End ( if ) condition for Macros */
		
}
