#include "ss_display.h"




/************************************************************************************************/
/************************************************************************************************/

void ss_display_vinit()
{
	//set ports as outputs
	dio_vidConfigChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,OUTPUT);
	dio_vidConfigChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,OUTPUT);
	dio_vidConfigChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,OUTPUT);
	dio_vidConfigChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,OUTPUT);
	
	dio_vidConfigChannel(SS1_DISPLAY_SELECTOR_PORT,SS1_DISPLAY_SELECTOR_PIN,OUTPUT);
	dio_vidConfigChannel(SS2_DISPLAY_SELECTOR_PORT,SS2_DISPLAY_SELECTOR_PIN,OUTPUT);
	dio_vidConfigChannel(SS3_DISPLAY_SELECTOR_PORT,SS3_DISPLAY_SELECTOR_PIN,OUTPUT);
	dio_vidConfigChannel(SS4_DISPLAY_SELECTOR_PORT,SS4_DISPLAY_SELECTOR_PIN,OUTPUT);
	
	//Write zeros on all digits
	dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_LOW);
	dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_LOW);
	dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_LOW);
	dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_LOW);
	
	#if (SS1_HW == COMMON_ANODE_CONFIGURATION)
		dio_vidWriteChannel(SS1_DISPLAY_SELECTOR_PORT,SS1_DISPLAY_SELECTOR_PIN,STD_LOW);	
	#elif (SS1_HW == COMMON_CATHODE_CONFIGURATION)
		dio_vidWriteChannel(SS1_DISPLAY_SELECTOR_PORT,SS1_DISPLAY_SELECTOR_PIN,STD_HIGH);
	#endif
	
	
	#if (SS2_HW == COMMON_ANODE_CONFIGURATION)
		dio_vidWriteChannel(SS2_DISPLAY_SELECTOR_PORT,SS2_DISPLAY_SELECTOR_PIN,STD_LOW);//
	#elif (SS2_HW == COMMON_CATHODE_CONFIGURATION)
		dio_vidWriteChannel(SS2_DISPLAY_SELECTOR_PORT,SS2_DISPLAY_SELECTOR_PIN,STD_HIGH);
	#endif
	
	
	#if (SS3_HW == COMMON_ANODE_CONFIGURATION)
		dio_vidWriteChannel(SS3_DISPLAY_SELECTOR_PORT,SS3_DISPLAY_SELECTOR_PIN,STD_LOW);//
	#elif (SS1_HW == COMMON_CATHODE_CONFIGURATION)
		dio_vidWriteChannel(SS3_DISPLAY_SELECTOR_PORT,SS3_DISPLAY_SELECTOR_PIN,STD_HIGH);
	#endif
	
	#if (SS4_HW == COMMON_ANODE_CONFIGURATION)
		dio_vidWriteChannel(SS4_DISPLAY_SELECTOR_PORT,SS4_DISPLAY_SELECTOR_PIN,STD_LOW);//
	#elif (SS4_HW == COMMON_CATHODE_CONFIGURATION)
		dio_vidWriteChannel(SS4_DISPLAY_SELECTOR_PORT,SS4_DISPLAY_SELECTOR_PIN,STD_HIGH);
	#endif
}

/************************************************************************************************/
/************************************************************************************************/

void ss_display_vwrite_num(u8 num)
{
	switch (num)
	{
		case (0):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_LOW);
			break;
		case (1):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_LOW);
		break;
		case (2):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_LOW);
		break;
		case (3):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_LOW);
		break;
		case (4):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_LOW);
		break;
		case (5):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_LOW);
		break;
		case (6):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_LOW);
		break;
		case (7):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_LOW);
		break;
		case (8):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_HIGH);
		break;
		case (9):
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN0,STD_HIGH);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN1,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN2,STD_LOW);
			dio_vidWriteChannel(SS_DISPLAY_DECODER_INPUT_PORT,SS_DISPLAY_DECODER_INPUT_PIN3,STD_HIGH);
		break;
		
	}
}